env:
  browser: true
  commonjs: true
  es2021: true
extends: [standard, prettier]
parserOptions:
  ecmaVersion: latest
rules: {semi: [2, 'always'], quotes: [2, 'double'], camelcase: 0, eqeqeq: ["null"]}
