FROM node:16.0.0 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY src src

FROM node:16.0.0

COPY --from=build /app /app

WORKDIR /app

ENV BACKEND_PORT ${PORT}

EXPOSE $BACKEND_PORT

CMD ["node", "src/app.js"]
