version: "3.4"
services:
  app:
    container_name: backend-ecommerce-desa-belega
    image: belega-village-unud/backend-api-edb:v1
    env_file:
      - ../.env
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - ecommerce-desa-belega
    depends_on:
      - db

  db:
    container_name: database-ecommerce-desa-belega
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DEV_DB_USERNAME}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
    ports:
      - ${DEV_DB_PORT}:5432
    networks:
      - ecommerce-desa-belega
    volumes:
      - db-data:/var/lib/postgresql/data

  sqlpad:
    container_name: sqlpad-ecommerce-desa-belega
    image: sqlpad/sqlpad:5
    hostname: "sqlpad"
    ports:
      - ${SQLPAD_PORT}:3000
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN_EMAIL}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_DB_PATH: /etc/sqlpad/ecommerce-data
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
      SQLPAD_CONNECTIONS__ecommerce-belega__name: Ecommerce Desa Belega
      SQLPAD_CONNECTIONS__ecommerce-belega__driver: postgres
      SQLPAD_CONNECTIONS__ecommerce-belega__host: ${STAGING_DB_HOST}
      SQLPAD_CONNECTIONS__ecommerce-belega__database: ${STAGING_DB_NAME}
      SQLPAD_CONNECTIONS__ecommerce-belega__username: ${STAGING_DB_USERNAME}
      SQLPAD_CONNECTIONS__ecommerce-belega__password: ${STAGING_DB_PASSWORD}
      SQLPAD_CONNECTIONS__ecommerce-belega__port: ${STAGING_DB_PORT}
      SQLPAD_CONNECTIONS__ecommerce-belega__multiStatementTransactionEnabled: "true"
      SQLPAD_CONNECTIONS__ecommerce-belega__idleTimeoutSeconds: 86400
    networks:
      - ecommerce-desa-belega
    volumes:
      - ecommerce-data:/etc/sqlpad/ecommerce-data

  prometheus:
    container_name: prometheus-ecommerce-desa-belega
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    expose:
      - ${PROMETHEUS_PORT}
    networks:
      - ecommerce-desa-belega
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - app
    volumes:
      - ../prometheus:/etc/prometheus
      - prometheus-config:/prometheus

  alertmanager:
    container_name: alertmanager-ecommerce-desa-belega
    image: prom/alertmanager
    ports:
      - ${ALERTMANAGER_PORT}:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
    volumes:
      - ../alertmanager:/etc/alertmanager
      - alertmanager-config:/etc/alertmanager
    networks:
      - ecommerce-desa-belega
    
  nginx:
    container_name: nginx-ecommerce-desa-belega
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../nginx:/etc/nginx/conf.d/:ro
      - ../../certbot/www:/var/www/certbot/:ro
    networks:
      - ecommerce-desa-belega
    depends_on:
      - app

  certbot:
    container_name: certbot-ecommerce-desa-belega
    image: certbot:certbot
    volumes:
      - ../../certbot/conf:/etc/letsencrypt/:rw
      - ../../certbot/www:/etc/www/certbot/:rw
    depends_on:
      - nginx

networks:
  ecommerce-desa-belega:
    driver: bridge

volumes:
  db-data:
    driver: local
  ecommerce-data:
    driver: local
  prometheus-config:
    driver: local
  alertmanager-config:
    driver: local
