version: "3.4"
services:
  duckdns:
    container_name: duckdns-ecommerce-desa-belega
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - SUBDOMAINS=belega
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    networks:
      - belega_service

  nginx:
    container_name: nginx-ecommerce-desa-belega
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/dhparam:/etc/nginx/dhparam
      - ../../certbot/conf:/etc/nginx/ssl
      - ../../certbot/data:/usr/share/nginx/html/letsencrypt
    networks:
      - belega_service

  certbot:
    container_name: certbot-ecommerce-desa-belega
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email ${ADMIN_EMAIL} --agree-tos --no-eff-email -d ${HOST}
    volumes:
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/logs:/var/log/letsencrypt
      - ../../certbot/data:/usr/share/nginx/html/letsencrypt
    networks:
      - belega_service

networks:
  belega_service:
    external: true
