version: "3.4"
services:
  duckdns:
    container_name: duckdns-ecommerce-desa-belega
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - SUBDOMAINS=belega
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    networks:
      - belega_service

  nginx:
    container_name: nginx-ecommerce-desa-belega
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/dhparam:/etc/nginx/dhparam
      - ../../certbot/conf:/etc/letsencrypt
    networks:
      - belega_service

  certbot:
    container_name: certbot-ecommerce-desa-belega
    image: infinityofspace/certbot_dns_duckdns:latest
    command:
      - certonly
      - --non-interactive
      - --preferred-challenges dns
      - --email ${ADMIN_EMAIL}
      - --agree-tos
      - --authenticator dns-duckdns
      - --dns-duckdns-token ${DUCKDNS_TOKEN}
      - --dns-duckdns-propagation-seconds 60
      - -d ${HOST}
    volumes:
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/logs:/var/log/letsencrypt
    networks:
      - belega_service

networks:
  belega_service:
    external: true
