version: "3.4"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/dhparam:/etc/nginx/dhparam
      - ../../nginx/cloudflare:/etc/nginx/cloudflare
    networks:
      - belega-network

networks:
  belega-network:
    external: true

