version: "3.4"
services:
  nginx:
    container_name: nginx-ecommerce-desa-belega
    image: nginx:latest
    ports:
      - 80:80
    deploy:
      mode: global 
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/dhparam:/etc/nginx/dhparam
      - ../../certbot/letsencrypt:/etc/letsencrypt
    labels:
      - "constraint:node==testing-environment"
    networks:
      - backend_testing_service

networks:
  backend_testing_service:
    external: true
