version: "3.4"
services:
  certbot:
    container_name: certbot
    image: nginx:latest
    ports:
      - 80:80
    command: certonly
      --non-interactive
      --agree-tos
      --email ${ADMIN_EMAIL}
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token ${DUCKDNS_TOKEN}
      --dns-duckdns-propagation-seconds 60
      -d ${DOMAIN_NAME}
    volumes:
      - ../../certbot/letsencrypt:/etc/letsencrypt
      - ../../certbot/logs:/var/log/etsencrypt

  certbot_cron:
    build: .
    container_name: certbot_cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CERTBOT_CONTAINER_NAME=certbot
