version: "3.4"
services:
  app:
    container_name: backend-ecommerce-desa-belega
    image: ghcr.io/belega-village-unud/backend-api-edb:staging
    env_file:
      - ../../.env
    restart: always
    ports:
      - ${PORT}:${PORT}
    deploy:
      mode: replicated 
      replicas: 2 
    networks:
      - service
    depends_on:
      - db
      - cache

  db:
    container_name: database-ecommerce-desa-belega
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DEV_DB_USERNAME}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
    ports:
      - ${DEV_DB_PORT}:5432
    networks:
      - service
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    container_name: cache-backend-ecommerce-desa-belega
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - service
    volumes:
      - cache-data:/data

networks:
  service:
    driver: overlay

volumes:
  db-data:
    driver: local
  ecommerce-data:
    driver: local
  cache-data:
    driver: local

