version: "3.4"
services:
  app:
    image: ghcr.io/belega-village-unud/backend-api-edb:staging-test
    env_file:
      - ../../.env
    deploy:
      resources:
       limits:
         cpus: "1.0"
         memory: "1G"
    ports:
      - target: 3333
        published: 3333
    networks:
      - belega-network

networks:
  belega-network:
    external: true

volumes:
  ecommerce-data:
    driver: local

