version: "3.4"
services:
  app:
    image: registry.belegacommerce.shop/belega-village-unud/backend-api-edb:${COMMIT_SHA}
    env_file:
      - ../../.env
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    ports:
      - target: ${PORT}
        published: ${PORT}
    networks:
      - belega-network

networks:
  belega-network:
    external: true

volumes:
  ecommerce-data:
    driver: local
