version: "3.4"
services:
  app:
    container_name: backend-ecommerce-desa-belega
    image: ghcr.io/belega-village-unud/backend-api-edb:staging-test
    env_file:
      - ../../.env
    restart: always
    ports:
      - ${EXPOSE_PORT}:${PORT}
    networks:
      - service
#    depends_on:
#      - db

#   db:
#     container_name: database-ecommerce-desa-belega
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=${DEV_DB_USERNAME}
#       - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
#       - POSTGRES_DB=${DEV_DB_NAME}
#     ports:
#       - ${DEV_DB_PORT}:5432
#     networks:
#       - service
#     volumes:
#       - db-data:/var/lib/postgresql/data

networks:
  service:
    driver: bridge

volumes:
#  db-data:
#    driver: local
  ecommerce-data:
    driver: local
