const ROLE = {
  BUYER: "BUYER",
  SELLER: "SELLER",
  ADMIN: "ADMIN",
};

const MODULE = {
  AUTH: "AUTH",
  PROFILE: "PROFILE",
  PRODUCT: "PRODUCT",
  SHOP: "SHOP",
  TRANSACTION: "TRANSACTION",
  LANDING: "LANDING",
  ADMIN: "ADMIN",
  SELLER: "SELLER",
  STORE: "STORE",
  FEE: "FEE",
};

module.exports = { ROLE, MODULE };
