name: Create and publish a API to Cloud Run

on:
  push:
    branches: ["staging"]

env:
  IMAGE_NAME: belega-commerce-api-image
  REPOSITORY: belega-commerce-api

jobs:
  ci-cd-api-docs:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CLOUD_RUN_SA }}
      - name: Docker configuration
        id: docker-config
        run: |-
          gcloud auth print-access-token \
            --impersonate-service-account ${{ secrets.CLOUD_RUN_SA }} | docker login \
            -u oauth2accesstoken \
            --password-stdin https://${{ secrets.REGION }}-docker.pkg.dev
      - name: Build
        run: |-
          docker build -f Dockerfile \
            --tag "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      - name: Tag Image with Latest
        run: |-
          docker tag "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA" \
            "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"
      - name: Publish
        run: |-
          docker push "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA"
          docker push "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.SERVICE_NAME }}
          region: ${{ secrets.REGION }}
          image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
      - name: Show Output
        run: |
          echo ${{ steps.deploy.outputs.url }}
          echo ${{ steps.deploy.image }}
