name: Deploy

on:
  push:
    branches: ["EDP-181-java-script-sast-with-eslint"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  INSTANCE_NAME: belega-instance
  REPOPATH: /home/${{ github.actor }}/backend-api-edb
  ZONE: asia-southeast2-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      actions: read
      packages: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CLOUD_RUN_SA }}

      - name: SSH to Compute Engine and Deploy
        id: compute-ssh-deploy
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: ${{ env.INSTANCE_NAME }}
          zone: ${{ env.ZONE }}
          ssh_private_key: ${{ secrets.SERVICE_ACCOUNT_SECRET_SSH_KEY }}
          user: ${{ github.actor }}
          command: "cd ${{ env.REPOPATH }}"
            
      - name: Test 
        id: compute-ssh-deploy-test
        run: |-
          git fetch
          pwd

